title: Piggy Pictures
author: Sarah Canata
email: angel.player100@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I tell you how everything works in piggy. You can ask questions and learn tips. Hope this is helpful!
theme: minima

# social links
twitter_username: PiggyPictures.com # DO NOT include the @ character, or else the build will fail!
github_username:  scannata # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
